version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "androidcore/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "androidcore/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew clean :core:test :androidcore:testEdinburghDebugUnitTest :app:testEdinburghDebugUnitTest
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_artifacts:
          path: app/build/reports
          destination: app-reports
      - store_artifacts:
          path: core/build/reports
          destination: core-reports
      - store_artifacts:
          path: androidcore/build/reports
          destination: androidcore-reports
      - store_test_results:
          path: ~/test-results